"""empty message

Revision ID: 71acb1c2b921
Revises: 
Create Date: 2017-09-01 21:50:53.699665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71acb1c2b921'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('paragraph_1', sa.VARCHAR(), nullable=True),
    sa.Column('paragraph_2', sa.VARCHAR(), nullable=True),
    sa.Column('paragraph_3', sa.VARCHAR(), nullable=True),
    sa.Column('paragraph_4', sa.VARCHAR(), nullable=True),
    sa.Column('paragraph_5', sa.VARCHAR(), nullable=True),
    sa.Column('paragraph_6', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
